apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            component: postgres
    template:
        metadata:
            labels:
                component: postgres
        spec:
            volumes:
                - name: postgres-storage
                  persistentVolumeClaim:
                    claimName: database-persistent-volume-claim                  
            containers:
                - name: postgres
                  image: postgres
                  ports:
                    - containerPort: 5432
                  # make this volume available inside this container
                  volumeMounts:
                    - name: postgres-storage
                      mountPath: /var/lib/postgresql/data # default path where Postgres saves data
                      subPath: postgres # subfolder created inside the persistent volume joined with mountPath - Postgres specific
                  # Secret object created locally for the db custom password (when someone tries to connect) with imperative command
                  # kubectl create secret generic <secret_name> --from-literal key=value
                  env:
                    - name: POSTGRES_PASSWORD
                      valueFrom:
                        secretKeyRef:
                            name: pgpassword
                            key: PGPASSWORD
