apiVersion: apps/v1
kind: Deployment
metadata:
    name: worker-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            component: worker
    template:
        metadata:
            labels:
                component: worker
        spec:
            containers:
                - name: worker
                  image: akakafonis/multi-worker
                  env:
                    - name: REDIS_HOST
                      value: redis-cluster-ip-service # name of the ClusterIP service it needs to connect to
                    - name: REDIS_PORT
                      value: '6379'